using LSC.PosAiWorkflow.Api.Configuration;
using LSC.PosAiWorkflow.Application.Abstractions.Services;
using LSC.PosAiWorkflow.Application.Replenishment.Dtos;
using LSC.PosAiWorkflow.Application.Replenishment.Services;
using LSC.PosAiWorkflow.Infrastructure.Persistence;
using LSC.PosAiWorkflow.Infrastructure.Persistence.Context;
using LSC.PosAiWorkflow.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace LSC.PosAiWorkflow.Api.Simulation;

public sealed class SimulationDataService
{
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly SimulationOptions _options;
    private readonly ILogger<SimulationDataService> _logger;

    public SimulationDataService(
        IServiceScopeFactory scopeFactory,
        IOptions<SimulationOptions> options,
        ILogger<SimulationDataService> logger)
    {
        _scopeFactory = scopeFactory;
        _options = options.Value;
        _logger = logger;
    }

    public async Task EnsureCatalogAsync(CancellationToken cancellationToken)
    {
        using var scope = _scopeFactory.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<PosAiWorkflowSimDbContext>();

        var productCount = await db.Products.CountAsync(cancellationToken);
        if (productCount >= _options.TargetProductCount)
        {
            return;
        }

        var templates = ProductCatalogTemplateProvider.GetTemplates().ToList();
        var needed = _options.TargetProductCount - productCount;
        var created = 0;
        var copyIndex = 1;

        while (created < needed)
        {
            foreach (var template in templates)
            {
                if (created >= needed) break;

                var sku = copyIndex == 1 ? template.Sku : $"{template.Sku}-{copyIndex:D2}";
                var exists = await db.Products.AnyAsync(x => x.Sku == sku, cancellationToken);
                if (exists) continue;

                var category = await db.Categories.FirstOrDefaultAsync(
                    x => x.Code == template.CategoryCode,
                    cancellationToken);

                if (category is null)
                {
                    category = new Category
                    {
                        Name = template.CategoryName,
                        Code = template.CategoryCode,
                        Description = $"{template.CategoryName} generated by simulator",
                        IsActive = true,
                        ScenarioName = "SimulationBootstrap",
                        IsSynthetic = true
                    };
                    db.Categories.Add(category);
                    await db.SaveChangesAsync(cancellationToken);
                }

                var product = new Product
                {
                    CategoryId = category.CategoryId,
                    Sku = sku,
                    Name = copyIndex == 1 ? template.Name : $"{template.Name} Variant {copyIndex}",
                    Description = template.Description,
                    UnitPrice = template.UnitPrice,
                    CostPrice = template.CostPrice,
                    ReorderThreshold = template.ReorderThreshold,
                    PreferredReorderQuantity = template.PreferredReorderQuantity,
                    LeadTimeDays = template.LeadTimeDays,
                    IsActive = true,
                    ScenarioName = "SimulationBootstrap",
                    IsSynthetic = true
                };

                db.Products.Add(product);
                await db.SaveChangesAsync(cancellationToken);

                db.StoreInventories.Add(new StoreInventory
                {
                    ProductId = product.ProductId,
                    StoreCode = _options.DefaultStoreCode,
                    QuantityOnHand = template.InitialQuantityOnHand,
                    QuantityReserved = template.InitialQuantityReserved,
                    ScenarioName = "SimulationBootstrap",
                    IsSynthetic = true
                });

                await db.SaveChangesAsync(cancellationToken);

                created++;
            }

            copyIndex++;
        }

        _logger.LogInformation("Catalog bootstrap completed. Created {CreatedCount} products.", created);
    }

    public async Task SimulateOrdersAsync(CancellationToken cancellationToken)
    {
        using var scope = _scopeFactory.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<PosAiWorkflowSimDbContext>();
        var orchestrator = scope.ServiceProvider.GetRequiredService<IReplenishmentWorkflowOrchestrator>();

        var random = Random.Shared;
        var orderCount = random.Next(1, _options.MaxOrdersPerCycle + 1);

        var products = await db.Products
            .Where(x => x.IsActive)
            .Join(
                db.StoreInventories.Where(i => i.StoreCode == _options.DefaultStoreCode),
                p => p.ProductId,
                i => i.ProductId,
                (p, i) => new
                {
                    Product = p,
                    Inventory = i,
                    DemandWeight = GetDemandWeight(p)
                })
            .ToListAsync(cancellationToken);

        if (products.Count == 0)
        {
            _logger.LogWarning("No products available for simulation.");
            return;
        }

        var impactedProductIds = new HashSet<long>();

        for (var i = 0; i < orderCount; i++)
        {
            var lineItemCount = random.Next(1, _options.MaxLineItemsPerOrder + 1);

            var order = new Order
            {
                OrderNumber = $"SIM-{DateTime.UtcNow:yyyyMMddHHmmssfff}-{random.Next(1000, 9999)}",
                OrderUtc = DateTime.UtcNow,
                CustomerName = $"Sim Customer {random.Next(1000, 9999)}",
                OrderStatus = "Completed",
                TotalAmount = 0,
                ScenarioName = "OrderSimulation",
                IsSynthetic = true
            };

            db.Orders.Add(order);
            await db.SaveChangesAsync(cancellationToken);

            decimal orderTotal = 0;

            var selectedProducts = products
                .OrderBy(_ => random.Next())
                .Take(lineItemCount)
                .ToList();

            foreach (var item in selectedProducts)
            {
                var maxSellable = Math.Max(1, item.Inventory.QuantityOnHand - item.Inventory.QuantityReserved);
                var quantity = Math.Min(random.Next(1, 4), maxSellable);

                if (quantity <= 0)
                {
                    continue;
                }

                var lineTotal = item.Product.UnitPrice * quantity;

                db.TransactionDetails.Add(new TransactionDetail
                {
                    OrderId = order.OrderId,
                    ProductId = item.Product.ProductId,
                    Quantity = quantity,
                    UnitPrice = item.Product.UnitPrice,
                    LineTotal = lineTotal,
                    ScenarioName = "OrderSimulation",
                    IsSynthetic = true
                });

                var before = item.Inventory.QuantityOnHand;
                item.Inventory.QuantityOnHand -= quantity;
                item.Inventory.LastStockUpdatedUtc = DateTime.UtcNow;

                db.InventoryAuditLogs.Add(new InventoryAuditLog
                {
                    ProductId = item.Product.ProductId,
                    StoreCode = _options.DefaultStoreCode,
                    ChangeType = "Sale",
                    QuantityBefore = before,
                    QuantityChanged = -quantity,
                    QuantityAfter = item.Inventory.QuantityOnHand,
                    ReferenceType = "Order",
                    ReferenceId = order.OrderId,
                    Reason = "Simulated order sale",
                    ScenarioName = "OrderSimulation",
                    IsSynthetic = true,
                    ChangedBy = "OrderSimulationService"
                });

                orderTotal += lineTotal;
                impactedProductIds.Add(item.Product.ProductId);
            }

            order.TotalAmount = orderTotal;
            await db.SaveChangesAsync(cancellationToken);
        }

        if (_options.EnableAutoReplenishmentTrigger)
        {
            foreach (var productId in impactedProductIds)
            {
                var shouldEvaluate = await ShouldTriggerReplenishmentAsync(db, productId, cancellationToken);
                if (!shouldEvaluate)
                {
                    continue;
                }

                await orchestrator.EvaluateAsync(new ReplenishmentDecisionRequestDto
                {
                    ProductId = productId,
                    StoreCode = _options.DefaultStoreCode,
                    ScenarioName = "AutoTriggeredSimulation"
                }, cancellationToken);
            }
        }
    }

    private async Task<bool> ShouldTriggerReplenishmentAsync(
        PosAiWorkflowSimDbContext db,
        long productId,
        CancellationToken cancellationToken)
    {
        var snapshot = await db.StoreInventories
            .Join(
                db.Products,
                i => i.ProductId,
                p => p.ProductId,
                (i, p) => new
                {
                    i.ProductId,
                    i.StoreCode,
                    QuantityAvailable = i.QuantityOnHand - i.QuantityReserved,
                    p.ReorderThreshold
                })
            .FirstOrDefaultAsync(
                x => x.ProductId == productId && x.StoreCode == _options.DefaultStoreCode,
                cancellationToken);

        if (snapshot is null)
        {
            return false;
        }

        var nearThreshold = snapshot.QuantityAvailable <= snapshot.ReorderThreshold + _options.ReplenishmentTriggerBuffer;
        if (!nearThreshold)
        {
            return false;
        }

        var cooldownFromUtc = DateTime.UtcNow.AddMinutes(-_options.ReplenishmentCooldownMinutes);

        var recentDecisionExists = await db.AiDecisions.AnyAsync(
            x => x.ProductId == productId
                 && x.StoreCode == _options.DefaultStoreCode
                 && x.CreatedUtc >= cooldownFromUtc
                 && (x.DecisionStatus == "PendingApproval"
                     || x.DecisionStatus == "AutoApproved"
                     || x.DecisionStatus == "Approved"),
            cancellationToken);

        return !recentDecisionExists;
    }

    private static int GetDemandWeight(Product product)
    {
        var name = product.Name.ToLowerInvariant();

        if (name.Contains("rice") || name.Contains("milk") || name.Contains("bread") || name.Contains("oil"))
            return 10;

        if (name.Contains("pasta") || name.Contains("soda"))
            return 7;

        if (name.Contains("soap") || name.Contains("detergent"))
            return 4;

        return 5;
    }
}